# Generated by Django 2.2.1 on 2019-05-10 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='lunbotu_image', verbose_name='轮播图片')),
                ('index', models.SmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='微博内容')),
                ('img', models.ImageField(blank=True, null=True, upload_to='bobo_image', verbose_name='微博图片')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='微博博主')),
            ],
            options={
                'verbose_name': '微博内容',
                'verbose_name_plural': '微博内容',
                'ordering': ['-create_time'],
            },
        ),
    ]
