# Generated by Django 2.2.1 on 2019-05-23 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bobo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoucang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('bo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobo.Bobo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
