# Generated by Django 2.2.1 on 2019-05-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bobo', '0002_shoucang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guanzhu11',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addguan_time', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('guanzhu_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
